### ISSUE TITLE
Please provide an example for adding ng-if to ivh-treeview-children

### ISSUE THREAD

**Issue by devsaik** [iVantage/angular-ivh-treeview#100]
In one of the optimization techniques it is  mentioned that  we can get performance benefits by adding ng-if to ivh-treeview-children. But on what condition, what expression should ng-if hold and  is this  a change that is required in ivh-treeview.js file

**Comment by jtrussell** [comment]
This optimization requires you to provide a custom template but you don't need to make any changes to the library itself. In your template you would only render child nodes if they would be visible, i.e. if the parent node is expanded: `<div ivh-treeview-children ng-if="trvw.isExpanded(node)"></div>`.

Here's a fully running demo: http://jsbin.com/momuro/2/edit?html,js,output

There are a number of other helpful methods exposed by the treeview controller which are available to you in your custom templates: https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md.

**Comment by devsaik** [comment]
Thanks Justin
