### ISSUE TITLE
Partially Selected Nodes

### ISSUE THREAD

**Issue by dineshmike** [iVantage/angular-ivh-treeview#101]
Is it possible to retrieve list of partially selected nodes?

Example :

[ - ] Node A
  * [ - ] Node AB <br />
    * [ o ] Node 1 <br/>
    * [  ] Node 2 <br/>

Selected Nodes : Node A, Node AB, Node 1

I can retrieve Node 1 using the selected property. Is there any way to select the parent nodes as well?

**Comment by jtrussell** [comment]
You can use the indeterminate property, it's usually `__ivhTreeviewIndeterminate` but you can be fully generic by grabbing the value from `ivhTreeviewOptions`:

```javascript
var selectedAttr = ivhTreeviewOptions.selectedAttribute
  , indeterminateAttr = ivhTreeviewOptions.indeterminateAttribute
  , myNodes = [];

ivhTreeviewBfs(myTree, function(node) {
  if(node[selectedAttr] || node[indeterminateAttr]) {
    myNodes.push(node);
  }

  // If you only care about top level selected nodes...
  if(node[selectedAttr]) {
    return false;
  }
});
```

An untested rough sketch but that's the idea. Does that help?

**Comment by dineshmike** [comment]
Sorry for late reply. Managed to work around by handling it on the server side. I passed the selected nodes and based on that found the parent nodes in DB. Thank you for your answer.

**Comment by jtrussell** [comment]
Cool, incidentally when using ivhTreeviewBfs to find a node it will also give you a list of its parent nodes. But that's regardless of whether they are selected or indeterminate.
