### ISSUE TITLE
How to select Nodes without using checboxes?

### ISSUE THREAD

**Issue by oxsav** [iVantage/angular-ivh-treeview#102]
Hello. 
U'm trying to select nodes without use checkboxes, I'm using the "ivh-treeview-on-cb-change", but this is only triggered when the checkbox state changes. 
Is possible to trigger this when we do a simple click on the node? 

Tks

**Comment by jtrussell** [comment]
Sure, you'll just need to create a custom node template. In your template attach `ng-click="trvw.toggleSelected(node)"` to whatever element you like. Note that you may also want to shift around which elements will expand/collapse the node when clicked.

Check out [the docs](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md) for more info on working with custom templates.

Closing, but feel free to follow up with additional questions :).
