### ISSUE TITLE
Set another node as root

### ISSUE THREAD

**Issue by lechat** [iVantage/angular-ivh-treeview#103]
Hi,

I have a large tree and sometimes I want to set some sub-node to be a root node and redraw existing treeview to reflect this. How do I do this?

Thanks!

**Comment by jtrussell** [comment]
What have you tried? The treeview directive should redraw if you give it a new root node. My first thought would be something like this:

```javascript
// in your controller...
var self = this;

var treeData = [/* all tree data */]; 

// Thing your pass to treeview, initially all the tree data
self.treeviewRoot = treeData

// Emit an event from your node when it should become the new root
$scope.$on('timewarpEvent', function(event, node) {
  self.treeviewRoot = node;
});
```
