### ISSUE TITLE
Is possible don't checked children?

### ISSUE THREAD

**Issue by Jenan** [iVantage/angular-ivh-treeview#105]
Hi,
I have a case where I need select parent item and I don't want to check its children.
Is possible do this in this plugin? Or when can I change specific part of code when it is cheched all children.
Thank you.

**Comment by jtrussell** [comment]
The easiest thing to do is to use a regular checkbox instead of the one provided by this directive in your template and just bind to the selected property of your node: http://jsbin.com/tokeso/2/edit?html,js,output

**Comment by AbhishekGarg** [comment]
@jtrussell I required the same functionality. But, I needed an option for turning the hierarchical selection off. I did think of using the template but there were too many trees where I would have to change this.

Please let me know if I can submit a PR for this.
