### ISSUE TITLE
Allow for Swapping Out of Primary Template

### ISSUE THREAD

**Issue by jkrot** [iVantage/angular-ivh-treeview#108]
I have slightly different markup needs and instead of forking the whole repo It would be nice to be able to just swap out the template.  I know you have different leaf template but I need to be able to change the entire markup.

**Comment by jtrussell** [comment]
What are you needs specifically that can't be addressed with the templating that's provided? Note that the templates apply to each node in the tree not just leaf nodes.

**Comment by jkrot** [comment]
I really need a html version of node.label that would bind to ng-bind-html,
 so that on a per node basis I can have some basic html formatting specific
to the date in each node.

**Comment by jtrussell** [comment]
Here's a demo with custom html in templates and node labels themselves:

http://jsbin.com/bogoyu/2/edit?js,output

Does that help?

**Comment by jkrot** [comment]
That does thank you.  If you want to reply to
http://stackoverflow.com/questions/35664106/custom-label-in-angular-ivh-treeview-that-allows-for-html
with
that I will give you credit for the answer.

**Comment by jtrussell** [comment]
Sure thing - glad to help.
