### ISSUE TITLE
How to use Angular Material

### ISSUE THREAD

**Issue by kasajian** [iVantage/angular-ivh-treeview#109]
Here's an example that uses the Angular Material checkboxes and icons

http://codepen.io/kasajian/pen/MyWyMo

**Comment by jtrussell** [comment]
Very sharp - if you want to swap that over to jsbin (just for consistency) I'd love to add it as an example in the docs.

**Comment by kasajian** [comment]
of course..   feel free to use it anyway you like.    So, are you asking me to put that on jsbin and the send you a link?  lemme know

**Comment by DevVersion** [comment]
@jtrussell @kasajian Definitely a good idea to document this.
- I'll discuss with the Material Team, about finding a place to share things like that.
Maybe we can create a section for community related shares.

https://github.com/angular/material/issues/7315

**Comment by jtrussell** [comment]
Very cool.

@kasajian Yeah, if you wouldn't mind porting your demo to jsbin that be awesome. I'd like to keep all the "official" demos for this repo using the same tool. Either way though thanks for sharing I'm sure folks will find it useful :).
