### ISSUE TITLE
Question: in the implementation of the 'Custom templates: transcluded' demo, how to avoid using global state

### ISSUE THREAD

**Issue by kasajian** [iVantage/angular-ivh-treeview#110]
In the demo for "Custom templates: transcluded" @ https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#template-helper-directives

It refers to the following jsbin: http://jsbin.com/jaqosi/edit?js,output

in the directive, there is this code:
```js
    link: function(scope, element, attrs) {
      element.on('click', function() {
        ivhTreeviewMgr.select(stuff, scope.node, !scope.node.selected);
        scope.$apply();
      });
```

I am surprised to see the use of `stuff` in the call to `ivhTreeviewMgr.select`.   Doesn't that make this directive applicable to only a single state of directive? 

So my question is whether this would be better:

```js
    link: function(scope, element, attrs) {
      element.on('click', function() {
        scope.trvw.toggleSelected(scope.node);
        scope.$apply();
      });
```

because everything is coming from a parameter.

if not, what would be another way to change the directive so that it is not relying upon a global or have intimate knowledge of the specific application?

**Comment by jtrussell** [comment]
Apologies for the confusion - there's no need to use a global state here.

The appropriate thing to do here would be to require `ivhTreevew` as a parent of the custom checkbox directive. Then you can get a reference to its controller in your link function which will provide a method `root()` that will get you a reference to the root of your tree. Updated demp here: http://jsbin.com/qihobe/2/edit?js,console,output

**Comment by jtrussell** [comment]
I updated the demo referenced by the docs as well :).
