### ISSUE TITLE
Children of children

### ISSUE THREAD

**Issue by FilipPoreba** [iVantage/angular-ivh-treeview#115]
It is possilbe to have children of children with custom names - not labels?

For example like this:

```
[{
                  name: 'name1',
                  date: '12.12.12',
                  children: [{
                    name: 'childname1',
                    date: '12.12.12',
                    children: [{
                         name: 'childchildname1'
                         date: '12.12.12'
                     }]
                  },{
                    name: 'childname2',
                    date: '11.11.11',
                    children: [{
                         name: 'childchildname2'
                         date: '11.11.11'
                     }]
                  }]
              }];
```

**Comment by Pavan1889** [comment]
Hi in below Code of your file chenge to your desired names:

angular.module('ivh.treeview').provider('ivhTreeviewOptions', function () {
    'use strict';

    var options = {
         /**
         * Collection item attribute to use for labels
         */
        labelAttribute: 'name', //'label' change here..

}}

For date you need to add new control beside label so for that you need solution something like below:
https://github.com/iVantage/angular-ivh-treeview/issues/114

**Comment by jtrussell** [comment]
Yes - you can use whatever property you like for your node labels on a case by case bases with [attribute level settings](https://github.com/iVantage/angular-ivh-treeview#options) or globally:

```javascript
app.config(function(ivhTreeviewOptionsProvider) {
  ivhTreeviewOptionsProvider.set({
    labelAttribute: 'label'
  });
});
```

If you want more control over your tree's appearance there is a lot of support for defining your own [node templates](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md).
