### ISSUE TITLE
Custom checkboxes

### ISSUE THREAD

**Issue by ErikvdVen** [iVantage/angular-ivh-treeview#116]
Is it possible to use custom checkboxes? I would love to use a custom style, which requires such HTML structure:
````
<div class="checkbox">
    <label>
        <input type="checkbox">
        <i class="fa fa-fw blank-check unchecked"></i>
        <i class="fa fa-fw fa-check checked"></i>
    </label>
</div>
````

**Comment by jtrussell** [comment]
Sure, you may have to do a little work if you want to keep the usual selection model though.

Check out the [transcluded template](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#inline-templates) example which builds some ASCII checkboxes: http://jsbin.com/jaqosi/edit?html,css,js,output

Alternatively, you can decorate `ivh-treeview-checkbox`.

**Comment by ErikvdVen** [comment]
Great, good to know, thanks!
