### ISSUE TITLE
Node Id Errors on Dynamic Data

### ISSUE THREAD

**Issue by jkrot** [iVantage/angular-ivh-treeview#122]
So this seems pretty straight forward but I can't figure out why this exception is occurring.  I am getting an error on ever node update when I am dynamically updating a $scope variable set to the data.   It throws exceptions at this code for every node as each node is loaded.   Changing validate, default selected state, and expand depth has no effect.  

```
  if(branch) {
    ivhTreeviewBfs(branch, opts, function(n, p) {
      n[expandedAttr] = isExpanded;
    });
  }
```

```
<div ivh-treeview="folder" class="treeview" ivh-treeview-expand-to-depth="1" ivh-treeview-default-selected-state="false" ivh-treeview-validate="false">
    <script type="text/ng-template">

            <div class="item" id="{{node.id}}">
                <span class="toggle" ivh-treeview-toggle>
                    <span ivh-treeview-twistie></span>
                </span>
                <span ng-if="trvw.useCheckboxes()" ivh-treeview-checkbox class="checkbox"></span>

                <span ng-bind-html="::trvw.label(node)" class="studynode"></span><span class='numoffiles'>{{node.children.length}}</span>

                <div ivh-treeview-children ng-if="trvw.isExpanded(node)" class="treeview-children"></div>
            </div>

    </script>
</div>
```

**Comment by jkrot** [comment]
There isn't a problem when the data is not dynamically loaded the only thing I can think of is to do a pull request so that treeview can handle a promise of data as well and doesn't update till that promise is resolved.

**Comment by jtrussell** [comment]
Yeah, ivhTreeview is definitely not designed to accept a promise - is that what `folder` is in your example code? It should handle a dynamic tree though. What's the error your seeing?

**Comment by jkrot** [comment]
src/scripts/services/ivh-treeview-mgr.js has the meat of the problem this entire function and all the of the nodes through isExpanded errors as shown above.

    exports.collapse = function(tree, node, opts) {
      return exports.expand(tree, node, opts, false);
    };

**Comment by jtrussell** [comment]
I see, thanks. Would you be able to stand up a demo on jsbin or plunkr? Also, are you trying to feed ivhTreeview a promise or an array of tree data?

**Comment by jkrot** [comment]
I will see if I can simplify the code enough to post publicly, it is a private repo.  Basically what happens is I start a disk read and start populating the values.  I create the main node, and start populating the children and children's children as well based on sorting of files.   So it builds sort of like this.

             Main Node                               Main Node
       /                                                  /                 \
   Child                                           Child             Child
    /                                                  /   \                      \
Grandchild                        Grandchild Grandchild   Grandchild

Where it is built from a top down aspect and I don't know how many grand children there will be till I am done parsing the files.  Though When I add files the child gets added with the grandchild at the same time.  I continue to add grandchildren to it till I hit a break then add a child with its own grandchild at the same time and continue adding grandchildren etc.

**Comment by jkrot** [comment]
Getting the data in from an online example is a pain since I am currently loading the nodes via file parsing,  I could rewrite an example just loading data dynamically with timeouts but that is going to take me awhile to stub that out.

**Comment by jkrot** [comment]
So my only solution to get around this is that any children that may have been created in a false <div ivh-treeview-children ng-if="trvw.isExpanded(node)" class="treeview-children"></div> was to not even have the tree handle generating those children but a separate directive to display them if the user wanted to see them.  Basically you have a eventing problem when you use ng-if on an non expanded node.  I could have used ng-show and the problem would have gone away since the nodes exist in the DOM but the performance bloat was just to much.

**Comment by jkrot** [comment]
Again I used a similar solution elsewhere using a custom boolean property for the node so that it wouldn't even try to execute code in the template if the property is note present.  Angular doesn't seem to puke on booleans note being defined but objects there were never going to be there cause it a headache.  

 <div ng-if="::node.file" title="{{trvw.label(node)}}">

 </div>
