### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by rtrompier** [iVantage/angular-ivh-treeview#123]
Hi guys,

Do you thing that is possible to do something like this, with the custom templating ? 

<img width="945" alt="screen shot 2016-04-14 at 09 14 15" src="https://cloud.githubusercontent.com/assets/2504924/14519786/5c393bc4-0221-11e6-927b-a51e9a78e172.png">

**Comment by jkrot** [comment]
I did something like that back in the day with a custom directive before multiple transclusion became all the rage.  I am assuming you don't want to populate the children items in the drop down till it is actually selected.

**Comment by jtrussell** [comment]
Definitely possible, but it looks like you could probably get by with just ngRepeat? Do need need nested structures like what you showed above or is it more accordion like?

**Comment by rtrompier** [comment]
Hi,
Thanks for your answers.
I have finally create my own tree hierarchy to manage my checkbox ;)
Maybe add a fully custom template features in this plugin will be great, or just the possibility to use the tree manager, without the directive in the angular view
