### ISSUE TITLE
It does't work with the Angular 1.5.5

### ISSUE THREAD

**Issue by RomanBogomolov** [iVantage/angular-ivh-treeview#127]
Fix please.

**Comment by jtrussell** [comment]
Seems ok to me - http://jsbin.com/zoqupucexe/1/edit?html,js,output

All tests pass against Angular@1.5.5 as well. Perhaps you could produce an example demonstrating your issue, you can clone the jsbin above or use the template in the README.

**Comment by RomanBogomolov** [comment]
To create an application using yoeman. My bower list consists of:
`
pwatcher#0.0.0 C:\FinalWebApp
├── angular#1.5.5 (1.5.6-build.4785+sha.707664a available)
├─┬ angular-animate#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5 (latest is 1.5.6-build.4785+sha.707664a)
├─┬ angular-cookies#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
├── angular-material#1.0.8 extraneous (1.1.0-rc4-master-f0e6de9 available)
├─┬ angular-material-data-table#0.10.9
│   ├── angular#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └─┬ angular-material#1.0.8 (1.1.0-rc4-master-f0e6de9 available)
│        ├── angular#1.5.5 (1.5.6-build.4785+sha.707664a available)
│        ├── angular-animate#1.5.5 (1.5.6-build.4785+sha.707664a available)
│        ├─┬ angular-aria#1.5.5 (1.5.6-build.4785+sha.707664a available)
│        │   └── angular#1.5.5
│        └─┬ angular-messages#1.5.5 (1.5.6-build.4785+sha.707664a available)
│             └── angular#1.5.5
├─┬ angular-mocks#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
├─┬ angular-resource#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
├─┬ angular-route#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
├─┬ angular-sanitize#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
├─┬ angular-touch#1.5.5 (1.5.6-build.4785+sha.707664a available)
│   └── angular#1.5.5
└─┬ bootstrap#3.3.6 (latest is 4.0.0-alpha.2)
     └── jquery#2.2.3 (latest is 3.0.0-beta1)
`

But when I try to install `bower install angular-ivh-treeview`, there is an error:

`
bower angular-ivh-treeview#*    cached https://github.com/ivantage/angular-ivh-treeview.git#1.0.3
bower angular-ivh-treeview#*  validate 1.0.3 against https://github.com/ivantage/angular-ivh-treeview.git#*
bower angular#~1.2.18           cached https://github.com/angular/bower-angular.git#1.2.29
bower angular#~1.2.18         validate 1.2.29 against https://github.com/angular/bower-angular.git#~1.2.18
bower angular#^1.4.8            cached https://github.com/angular/bower-angular.git#1.5.5
bower angular#^1.4.8          validate 1.5.5 against https://github.com/angular/bower-angular.git#^1.4.8
bower angular#1.5.5             cached https://github.com/angular/bower-angular.git#1.5.5
bower angular#1.5.5           validate 1.5.5 against https://github.com/angular/bower-angular.git#1.5.5
bower                        ECONFLICT Unable to find suitable version for angular
`
Can you help me, please? Thank you!

**Comment by jtrussell** [comment]
I see - I think you can still(?) resolve these sorts of conflicts in your bower.json file with a `resolve` block.

In any case there's nothing in this module that shouldn't work with 1.4 or 1.5 so I updated our dependencies to explicitly allow those versions too - you shouldn't have any issues now if you try again:

```
bower install angular-ivh-treeview
```

Just be sure it's fetching v1.0.4 or greater :).

**Comment by RomanBogomolov** [comment]
Excellent! Thank you :)
