### ISSUE TITLE
After filter the resultant children's will not expand 

### ISSUE THREAD

**Issue by NitheshJain** [iVantage/angular-ivh-treeview#128]
if i try to search some node in tree, the resultant tree with matched node will not allow to expand his child node, please help me regarding.
I have linked image **before filter & after filter** please have look

Before filter:
http://postimg.org/image/oumyq3kxt/

After filter:
http://postimg.org/image/c8qbyhmm9/

**Comment by jtrussell** [comment]
The filter is actually behaving as expected - your child nodes don't have the string `CHILE` in them and so are being hidden. If you'd like to keep child nodes visible when a parent is matched by the filter string I'm afraid you'll need to provide your own function to filter with.

**Comment by srk289** [comment]
@jtrussell sorry to post in closed issue. I just want to know if there is an example of providing our own function to filter. Thanks in advance

**Comment by jtrussell** [comment]
Sure: http://jsbin.com/yadevayuga/1/edit?html,js,output

**Comment by stu-co** [comment]
Sorry to post in a closed issue, but I was wondering if @srk289 or @NitheshJain ended up solving this in an open source way?

I'll need to write my own solution to this shortly if not!
