### ISSUE TITLE
Bind filter to ng-keypress

### ISSUE THREAD

**Issue by NitheshJain** [iVantage/angular-ivh-treeview#130]
Currently filter is bind to ng-change event. I have tried to change it to ng-keypress, The reason behind this, i don't want to call filter for each and every character change, instead bind to  ng-keypress (Enter key) will call filter only after complete input (String) and press Enter.

i tried some thing like this: 

 <input type="text" ng-model="getString" ng-keypress="searchChangeCallback(getSearchLocation, $event)"  />
 <input type="hidden" ng-model="setString" />

            <div class="locationTreeResult" 
            	ivh-treeview="locationTree"
            	ivh-treeview-filter="setString" 
            	ivh-treeview-on-cb-change="Callback(ivhNode,ivhIsSelected,ivhTree)" ></div>
Am setting value to ng-model="setString" in controller, the filter working fine, But after clearing ng-model="setString" value tree will not reset to original tree

**Comment by jtrussell** [comment]
Would you mind providing an example to demonstrate the issue and your setup? There's a jsbin template in the README: https://github.com/iVantage/angular-ivh-treeview#reporting-issues-and-getting-help.

**Comment by jtrussell** [comment]
Closing but feel free to reopen with a demo.
