### ISSUE TITLE
Double clicking leaf node

### ISSUE THREAD

**Issue by leggebroten** [iVantage/angular-ivh-treeview#134]
Hi,

I'm using your tool to simulate a file folder.
I can't find a way to insert a double click event on leaf nodes.  
(ng-dblclick on in nodeTpl doesn't work either)

Suggestions?

Thanks in advance

-Lee

**Comment by jtrussell** [comment]
Hey @leggebroten, there's no reason `ng-dblclick` shouldn't work within a node template (that I know of). Would you mind demonstrating the issue using the [starter template in the README](https://github.com/iVantage/angular-ivh-treeview#reporting-issues-and-getting-help)?

**Comment by jtrussell** [comment]
Closing this for now but we'll reopen with a reproduction of the issue.
