### ISSUE TITLE
I want to select the parent node when the node is selected.

### ISSUE THREAD

**Issue by anhuisunfei** [iVantage/angular-ivh-treeview#138]
I want to select the parent node when the node is selected.

**Comment by jtrussell** [comment]
Sorry, I'm not 100% sure what you mean. Perhaps you could provide an example to illustrate?

In any case, the baked in selection management is tied to the `ivh-treeview-checkbox` sub-directive. In your custom template you can easily swap that out for your own checkbox to handle selections however you like.

**Comment by jtrussell** [comment]
Also, check out the [templates and skins doc](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md) if you haven't already. There's lots of info to get you going with custom tree node templates if you aren't familiar with using them.

**Comment by anhuisunfei** [comment]
thanks! 
closes #137

**Comment by anhuisunfei** [comment]
closed #137

**Comment by anhuisunfei** [comment]
close #137

**Comment by anhuisunfei** [comment]
thanks

**Comment by anhuisunfei** [comment]
tnaks
