### ISSUE TITLE
Expanding to selected nodes when data is set

### ISSUE THREAD

**Issue by jfoshee** [iVantage/angular-ivh-treeview#139]
I would like to expand the tree to reveal the selected nodes when the bound `ivh-treeview` data changes.

This would be a nice feature.  Short of having the feature, is there a way I can code this myself? I would need access to the `trvw` object after it is created, or after the data is loaded...  But, I do not see a handler for that...  How early can I get a `trvw` object?

Thanks for sharing this library! :+1:

**Comment by srk289** [comment]
@jfoshee I am trying to achieve the same. Did you find a way to expand the parent nodes when child nodes are selected?

**Comment by jfoshee** [comment]
I initially thought this was more complicated than it was.  I misunderstood what `tree` object was expected by the `ivhTreeviewMgr` utility functions. It is, in fact, the same object that you bind the tree view to. (Not the `trvw` as I was thinking.)  

So for example, for a given binding:

    <div ivh-treeview="choices" ...> </div>

In my controller (using [TypeScript](https://www.typescriptlang.org/) and [UnderscoreJS](http://underscorejs.org/)):

        private expandToSelectedNodes(): void {
            var selectedNodes = this.getSelectedNodes(this.$scope.choices);
            _.forEach(selectedNodes, node =>
                this._ivhTreeviewMgr.expandTo(this.$scope.choices, node, this.ivhOptions, true));
        }
    
        private getSelectedNodes(nodes: ParameterTreeNode[]): ParameterTreeNode[] {
            var parents = _(nodes).filter(node => node.IsSelected);
            var children = _(nodes).map(node => this.getSelectedNodes(node.Children));
            return _.flatten([parents, children]);
        }

I believe you can also get the selected nodes using `ivhTreeviewBfs`, but I'm not sure how.
