### ISSUE TITLE
How to add radio buttons in sub nodes click?

### ISSUE THREAD

**Issue by amardhere** [iVantage/angular-ivh-treeview#141]
I need tree view with check box and radio buttons. Tree view required 3 levels and on click of 3rd level sub node need to show radio buttons.
Is it possible this with angular-ivh-treeview ? where I need to do changes?

I have some more queries of followings -
Is "angular-kendo.js" free to use in the application? 
Is it required any license cost ? 
Is "angular-kendo.js" part of Kendo or separately developed ?

**Comment by jtrussell** [comment]
It is possible. You will want to create a custom node template for this directive to use, please see the docs here:

https://trello.com/c/c8hx68ty/490-add-option-to-autocode-skillmix-for-any-facility-regular-fcr-21

Note that you have access to a `depth` variable in scope for you templates to use:

https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#supported-template-scope-variables

Sorry, I don't know about your Kendo questions but this directive does not require a fee to use.
