### ISSUE TITLE
Custom filter function

### ISSUE THREAD

**Issue by sajithpc** [iVantage/angular-ivh-treeview#142]
Used below code to write custom filter function.

`<div ivh-treeview="demo.stuff"
         ivh-treeview-expand-to-depth="1"
         ivh-treeview-filter="demo.specialFilterFn">`

Controller method is given below:
`self.specialFilterFn = function(node) {
    return self.showSelectedOnly ?
      node.selected :
      true;
  };`

The actual filter method is setting isVisible property and ng-hide to keep the filtered nodes out of display. But whatever selections made via checkboxes are applied on non-displayed nodes as well. Is it possible override this feature with actually filter ivhModel so that it will reflect what is viewable and any actions are done in visible nodes are applied in that only, instead of hidden nodes.

Please clarify is this possible to achieve.

**Comment by jtrussell** [comment]
The built in filters will always merely toggle visibility and have no effect on selection.

Your only option would be to use a custom template and manage selection changes (checkboxes) yourself. From a clicked node you can gather children with `ivhTreeviewBfs` and choose which to toggle using [`trvw.isVisible`](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#supported-template-scope-variables).
