### ISSUE TITLE
Does ivh tree view has drag and drop support?

### ISSUE THREAD

**Issue by iyip** [iVantage/angular-ivh-treeview#143]
Does ivh tree view has drag and drop support? Say I've selected some nodes in the tree by checking the checkboxes, and I'd like to drag those nodes and drop them into another UI control on the page, is this supported? 
Thanks

**Comment by jtrussell** [comment]
Sorry, there's no support for drag and drop out of the box. You can however implement drag and drop adding the appropriate listeners to your node templates or theoretically dropping in something like angular-dragdrop.

That would make for an interesting demo actually, let me know if you do try it and have a working example you could share. I'll update the site with an example once a get a moment to try it out too.
