### ISSUE TITLE
Failed to execute "git clone"

### ISSUE THREAD

**Issue by amitdun** [iVantage/angular-ivh-treeview#145]
Failed to install ivh-treeview with bower component.
Failed to execute "git clone https://github.com/ivantage/angular-ivh-treeview.git -b v1.0.4 --progress . --depth 1", exit code of #-532462766

**Comment by jtrussell** [comment]
Seems to be working fine for me and I don't believe that's an expected error code from either git or bower.

Can you confirm this is still happening and provide some details of your setup and system?

**Comment by amitdun** [comment]
this issue was with VS2015, I have resolved.
