### ISSUE TITLE
Image in label

### ISSUE THREAD

**Issue by RomaHL** [iVantage/angular-ivh-treeview#147]
If it possible to add image to label or html-code?

**Comment by diimpp** [comment]
It's possible.

Everything already in the docs.
https://github.com/iVantage/angular-ivh-treeview#options
https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md

**Comment by RomaHL** [comment]
Ok, I do it with template, but what about checkboxes. 
Is it possible customizing it, add some label for it or replace with other HTML, but it must work like with default checkboxes.
I wont replace default checkboxes with this template, 
but keep default functionality:
 `<div class="checkbox"><label><input type="checkbox" class="ivh-treeview-checkbox"><span class="checkbox-material"><span class="check"></span></span></label></div>`

**Comment by diimpp** [comment]
I see, you want to change template of checkbox directive https://github.com/iVantage/angular-ivh-treeview/blob/master/src/scripts/directives/ivh-treeview-checkbox-helper.js ?

I don't think changeable template is supported at this directive. Maybe you can try some angular hackery to override template var http://angular-tips.com/blog/2013/09/experiment-decorating-directives/

By most probably you don't need to change it and example at https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#inline-templates should be sufficient for you.
This way it seems to allow add label around checkbox or other html elements.

**Comment by jtrussell** [comment]
@diimpp is correct, the checkboxes themselves don't support templating. However, they're really just sitting on top of `ivhTreeviewMgr#select`. Wiring up your own checkboxes to use this service is not too difficult.

[Here's a silly demo showing custom checkboxes](http://jsbin.com/fokunu/edit?html,js,output) with the relevant code below.

```javascript
app.directive('asciiBox', function(ivhTreeviewMgr) {
  return {
    restrict: 'AE',
    template: [
      '<span class="ascii-box">[',
        '<span ng-show="node.selected" class="x">x</span>',
        '<span ng-show="node.__ivhTreeviewIndeterminate" class="y">~</span>',
        '<span ng-hide="node.selected || node.__ivhTreeviewIndeterminate"> </span>',
      ']</span>',  
    ].join(''),
    link: function(scope, element, attrs) {
      element.on('click', function() {
        ivhTreeviewMgr.select(stuff, scope.node, !scope.node.selected);
        scope.$apply();
      });
    }
  };
});
```
