### ISSUE TITLE
parent node selection status not updated when child's selected property changed by binding

### ISSUE THREAD

**Issue by fhurta** [iVantage/angular-ivh-treeview#150]
Normally, parent node's `selected` state reflects the state of its children - if no/all/some children are `selected`. The icon has meaning either checked, unchecked or (some children checked, some not).

If the child's `selected` property is changed from code, the binding changes its 'selected` state (the icon) but the parent's state is not changed.

See this [jsbin](http://jsbin.com/teyikujaka/1/edit?html,js,output). After loading, all the Pens node and its children are selected. Click the button **Unselect Fountain** - it changes `selected` state for Pens -> Fountain item to `false` and the item is unchecked, but the Pens node still looks like all its children are selected.

(If you change the `selected` state on Fountain by click then the Pens state is updated.

**Comment by jtrussell** [comment]
Yes, this behavior is by design. If you'd like to update your selection programmatically you have a couple options:

- Use the [ivhTreeviewMgr#select](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrselecttree-node-opts-isselected)
- Update nodes as you have done in your example then use [ivhTreeviewMgr#validate](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrvalidatetree-opts-bias)

**Comment by fhurta** [comment]
Thanks. Tried that but `ivhTreeviewMgr.deselect()` does not work me. See [this](http://jsbin.com/jacefanixa/edit?html,js,output). The difference from your demo is the name of `selectedAttribute` and specifying the options on controller. However it works when the options are specified using module's config() method.

**Comment by jtrussell** [comment]
The `ivhTreeviewMgr` service is a global (as are all Angular services). On the other hand you may have multiple treeview instances on the page, each with a different configuration. As such, `ivhTreeviewMgr` is not tied to the specific options of any one treeview instance. If you have a treeview using options that differ from your global settings you will want to provide those same options to `ivhTreeviewMgr` or it will assume the global options.
