### ISSUE TITLE
Filtering - some single letter filters do not work

### ISSUE THREAD

**Issue by fhurta** [iVantage/angular-ivh-treeview#151]
I tried filtering but for some characters it does not work. Verified with your filtering [demo](http://jsbin.com/zitiri/edit?html,output).

Try to type single character into filter input, eg. `s`, `f` or `e` -> the tree does not hide anything.
For character 'r', some items get hidden but not  'Fountain' or 'Gel ink' for example

**Comment by jtrussell** [comment]
Angular filters by default search against **all** object properties when you just provide a string filter. This means things other than your label will be considered - including the **selected** property which is a boolean that Angular coerces to a string while filtering. The letters `s`, `f`, and `e` are all part of the word `false` (i.e. `selected: false`).

To get behave that's a bit more sane you have a couple options.

You can use an object filter and specify the properties to filter against, e.g. `ivh-treeview-filter="{label: myFilterVar}"`.

Or you can use a filter function, e.g. `ivh-treeview-filter="myFilterFn"`. Where `myFilterFn` gets passed each tree node individually and can return `true` or `false` to show/hide it (i.e. each node is treated as an array of length 1 and forwarded to `filterFilter`).

**Comment by fhurta** [comment]
Cool, thanks!
