### ISSUE TITLE
UMD compatibility?

### ISSUE THREAD

**Issue by nkovacic** [iVantage/angular-ivh-treeview#156]
Loader support (browserify, RequireJS, webpack) is missing.
Is there a plan to incorporate them into angular-ivh-treeview?

**Comment by jtrussell** [comment]
There are no such plans simply because we aren't using those tools at iVantage for our AngularJS apps.

We would be open to a PR adding UMD boilerplate as a build step though.

**Comment by ebramanti** [comment]
@nkovacic Did you ever implement a UMD solution for this?

**Comment by nkovacic** [comment]
Unfortunately not :(. The version 2 is around the corner so there is little chance it will ever be implemented.
