### ISSUE TITLE
Add <label> for input[checkbox] to make possible style checkboxes with css

### ISSUE THREAD

**Issue by IvannaBesarab** [iVantage/angular-ivh-treeview#159]
Hello, thank you much for sharing such handy component!

Now i have an issue  to style checkboxes (selected/ not selected)  with css. Could you, please, add label element to each input ?  Or there are other ways how i can style input ?

**Comment by jtrussell** [comment]
The [templates and skins](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#tree-layout) document lays out the supported class names  and nested structure for the default template. If that doesn't work for you though (it is intended to be minimal) we definitely encourage you to use a custom template where you could absolutely associate an actual label element with each checkbox.

I don't think we will modify the default template to include checkbox labels as we want a label click to hide/show child elements and not toggle the checkbox state. There are a bunch of examples on that page too for setting up custom templates. Give a shout if you run into any issues.
