### ISSUE TITLE
Additional Checkboxes

### ISSUE THREAD

**Issue by mgamperl** [iVantage/angular-ivh-treeview#160]
Hi,

for a project of mine I do need additional checkboxes per node (think of a tree with permissions: view, read, write). 
I think the cleanest way to achieve that would be to enhance the ivh-treeview with a functionality that you have additional "selection attributes" and methods like `select` or `selectAll` take an optional parameter to specify which type of selection to modify.

I am willing to do a pull request for that if you think that this kind of functionality may be interesting for you. If so we should talk a little bit about how to implement it before I start working, to meet your expectations of backwards compatibility and other ideas you may already have.

Thanks and
Best Regards

**Comment by jtrussell** [comment]
Can you accomplish this already with node templates and `ivhTreeviewMgr` while specifying the attribute to use for tracking selections?

**Comment by mgamperl** [comment]
@jtrussell thank you for your quick response, I have checked it and yes, you are completely right, it can be done easily with a custom template and ivhTreeviewMgr.

Thank you for your time and the awesome work!

I will close this issue, as my question is answered.

**Comment by jtrussell** [comment]
Awesome! Glad that works for you :).
