### ISSUE TITLE
How to implement a single selection mode?

### ISSUE THREAD

**Issue by rudaoshi** [iVantage/angular-ivh-treeview#165]
I actually want just a call back when I click the label of the node, however, there only one way to do this is via cb-change call back. 

However, when I call mgr.deselectAll in the cb-change call back, nothing happens. So I cannot implement the single selection model. 

How could I do this?

**Comment by jtrussell** [comment]
The ivh-treeview selection management strategy is tied to the [ivh-treeview-checkbox](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#template-helper-directives) helper directive. Trying to change the selection strategy without using a custom template will be difficult :).

If you need to handle selections differently you'll want to use a custom template with your own checkboxes. In your example above are you providing a reference to the tree to `ivhTreeviewMgr.deselectAll`?
