### ISSUE TITLE
set limit to treeview 

### ISSUE THREAD

**Issue by kamotext** [iVantage/angular-ivh-treeview#166]
for example i have a data with a structure up to 4th level, is there any way i can limit the treeview to 2nd or 3rd only?

**Comment by jtrussell** [comment]
You can do this but you'll need custom node template.

Template scopes have a `depth` variable you can use which corresponds to the how deep in the tree that node resides. You can use this variable with `ng-if` on the `ivh-treeview-children` element to stop rendering child nodes after a certain depth.
