### ISSUE TITLE
Don't select all children when parent node is selected

### ISSUE THREAD

**Issue by slavafomin** [iVantage/angular-ivh-treeview#171]
Hello!

Thank you for this great module!

However, is it possible to prevent automatic selection of all children nodes when parent node is selected?

Also, when one of children nodes is selected, the parent node has a minus sign instead of a checkbox, is it possible to always display checkboxes?

I want to implement a behavior when all parents of the node are automatically selected when the node is selected. And parent node should be also selectable even if no children are selected.

The component here is working almost exactly like I want it: http://a5hik.github.io/angular-multi-select-tree/. Is it possible to replicate this behavior with **ivh-treeview**?

Thanks!

**Comment by jtrussell** [comment]
This is possible - you'll just want to use your own checkboxes in your template instead of the ones that ship with this directive. A simple `ng-model` connecting the node's select property to your checkbox should do the trick.
