### ISSUE TITLE
Parent selection when not all children are selected.

### ISSUE THREAD

**Issue by riteshbhoi** [iVantage/angular-ivh-treeview#184]
Scenarios where i have to set selection of the tree programatically (when tree values are loaded dynamically), i don't see any option to mark the parent as semi-selected (din't get any better word) when not all the children are selected. I just see option to mark parent as selected or not.

I see that using attribute "ivh-treeview-validate" to true, tree will be validated and above scenario can be handled. But when the tree values are lazy loaded (say some API calls), then in that case setting "ivh-treeview-validate" to true, doesnt help. This only works when tree values are set on load.

**Comment by riteshbhoi** [comment]
ok, so i ended up invoking ivhTreeviewMgr.validate(tree) after i initialize the variable which contains my tree value i.e. the value to be bound to the checkbox. Is that the only way to achieve that?

**Comment by jtrussell** [comment]
How are you marking nodes as selected? `ivhTreeviewMgr.select(tree, node)` ([link](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrselecttree-node-opts-isselected)) should take care of validating the parents and children of the node you're selecting. On the other hand, setting a node's selected state manually - e.g. `myNode.selected = false` - is not a "managed" operation and would require re-validating tree if you wanted to remain consistent with our selection model.

**Comment by riteshbhoi** [comment]
yeah, i am selecting state manually i.e. node.selected = false. I will try the other way suggested by you. Thank you.
