### ISSUE TITLE
How can I check an node, but don't toggle it's parent node?

### ISSUE THREAD

**Issue by glossary95** [iVantage/angular-ivh-treeview#186]
I hope when the user click the check box of a node, but can't cascade  the check box of the parent node. Is there some option for this case? and what is it? Thank you very much for your answers.

**Comment by glossary95** [comment]
I try to set the option of the tree 'validate: false', but it still check cascade. who have some idea for this case. Thank you!

**Comment by jtrussell** [comment]
There's no option to configure the built in selection model. In this case you'll want to use your own checkbooks in a custom template and implement your desired behavior.

**Comment by glossary95** [comment]
thanks a lot
