### ISSUE TITLE
Latest version (v2.0.0-alpha.3) not released in npm yet

### ISSUE THREAD

**Issue by christophercr** [iVantage/angular-ivh-treeview#191]
Hi,

I've tried to install the latest version of branch 2 (v2.0.0-alpha.3) using NPM but the latest release in NPM is v2.0.0-alpha.2 which still has the old dist files.

Could you please release the latest version (including the latest dist files) in npm?

**Comment by jtrussell** [comment]
v2.0.0-alpha.4 is published with updated dist files.
