### ISSUE TITLE
ERROR in ./~/angular-ivh-treeview/gruntfile.js

### ISSUE THREAD

**Issue by gangyeona** [iVantage/angular-ivh-treeview#193]
hi,firstly thanks for shareing this tree

after i run "npm install angular-ivh-treeview --save"，it has a error 

'ERROR in ./~/angular-ivh-treeview/gruntfile.js
Module not found: Error: Cannot resolve module 'matchdep' in /git/pro/power/node_modules/angular-ivh-treeview
 @ ./~/angular-ivh-treeview/gruntfile.js 123:2-21'

it seems to about grunt? but i use webpack in my pro,how i should do?

**Comment by jtrussell** [comment]
This is strange - `matchdep` is a dev dependency used by the gruntfile, it's not installed for production use. If you require or import the `angular-ivh-treeview/gruntfile.js` in production you will see this error... I'm just not sure how you'd go about requiring or importing it unless you were do so explicitly. Do you get this error *immediately* after running the `npm install` command or after running something else?

Aside - really, we shouldn't even get the gruntfile when you install this module :/ (we need to declare a `files` property in our packages.json). I created #194 for this which would probably solve your issue but there is likely something else going on.

**Comment by gangyeona** [comment]
i import  `angular-ivh-treeview` in production.just now i  import `dist/ivh-treeview.js`
`dist/ivh-treeview.css`
`dist/ivh-treeview-theme-basic.css` 3 files，then it works！
thanks
