### ISSUE TITLE
How to programmatically select nodes using ivh-treeview-mgr without also selecting their children?

### ISSUE THREAD

**Issue by kevinkuszyk** [iVantage/angular-ivh-treeview#195]
I'm using the `ivh-treeview-mgr` to select some nodes in my tree.  Whilst it's working great and parents are selected, I don't want it to also select the child nodes.

Is this possible with the `ivh-treeview-mgr` at present?  If not, if you can give me some direction I'd be happy send a PR which adds this as an option to the `.select()` method.

**Comment by jtrussell** [comment]
The [select method](https://github.com/iVantage/angular-ivh-treeview/blob/master/src/scripts/services/ivh-treeview-mgr.js#L105-L140) essentially does three things:

- Finds the node you intend to select
- Selects it and all child nodes
- Validates the state of parent nodes (marks a selected, deselected, indeterminate)

If you wanted to make the selection model behavior configurable you could so by adding new options to the `ivhTreeviewOptionsProvider` and branching on that in the select method. We'd just want to think of the different behaviors we wanted to support.

**Comment by kevinkuszyk** [comment]
Thanks @jtrussell, I've made a start, but I can't see where the loops in the `select()` method it actually selects the children (or calls out to loop over them)?

I also had some problems getting the grunt tasks to run on my machine (I didn't have node 0.10), so made a docker file which creates an image with the correct tooling installed.  Would you be interested to have this included in the PR too?

**Comment by jtrussell** [comment]
To be honest I'm not terribly interested in maintaing a dockerfile for this repo in perpetuity. I'd like to think that most vanilla node docker environments would be pretty close to sufficient for folks who want to go that route. We tend to use nvm for managing local node version too ¯\_(ツ)_/¯. I *would* be more interested in updating the dev tooling to work with modern node though that likely deserves a separate PR.

[This line] kicks off a traversal of the tree started at the node-to-be-selected-or-deselected, updating it and all children to match.

**Comment by kevinkuszyk** [comment]
> To be honest I'm not terribly interested in maintaing a dockerfile for this repo in perpetuity

No problem, I'll drop that commit from my branch before I push it.

> [This line] kicks off a traversal of the tree...

You forgot to paste the actual link in there!

**Comment by jtrussell** [comment]
Fixed :)

**Comment by kevinkuszyk** [comment]
Thanks for your help with this.

It turns out we have forked the treeview control, and the code I started in [my fork](https://github.com/kevinkuszyk/angular-ivh-treeview/commits/develop) won't work in our app.

There is some working code in my fork.  Feel free to grab it if you want, as it's unlikely I'll get time to finish it off and open a PR.
