### ISSUE TITLE
Disabling propagation of selection (checkboxes)

### ISSUE THREAD

**Issue by fhurta** [iVantage/angular-ivh-treeview#199]
Is it possible to disable propagation of selection in checkboxes?
I mean if I select (check the checkbox) a node which is not leaf the children nodes have not have their checkbox checked?  I.e. each node's checkbox is completely independent of others?

**Comment by jtrussell** [comment]
There's no explicit option to do this. Your best bet is to use a different checkbox than the helper directive provided here. Then you can just bind directly to the checkbox input and do whatever you like with it.

There are a few older issues as well that might give you some ideas. We even had some discussion around a PR to add this functionality if you're interested to work on it: https://github.com/iVantage/angular-ivh-treeview/issues/195.
