### ISSUE TITLE
ivh-treeview-children-attribute does not override default config

### ISSUE THREAD

**Issue by iandroogmans** [iVantage/angular-ivh-treeview#203]
While wanting to change the children-attribute for a specific tree, i noticed my getChildren().length was always zero.

```
<div class="streamgroups-tree"
     ivh-treeview="$ctrl.streamgroups"
     ivh-treeview-children-attribute="'childStreamGroups'"
     ivh-treeview-on-cb-change="$ctrl.treeUpdated()">
```

With previous config, i received following (example) output

```
node.childStreamgroups.length = 3
getChildren().length = 0
```
When i updated the option in the ivhTreeviewOptionsProvider it worked perfectly and getChildren().length was also 3.

```
ivhTreeviewOptionsProvider.set({
   childrenAttribute: 'childStreamGroups'
});
```

Things i've tried:

- Using another key name
- Setting the value via a controller variable instead of plain string
- Adding options via ivh-treeview-options with controller variable & object directly in attribute
- Printing out multiple variables

**Comment by jtrussell** [comment]
Hmm... that's interesting. Nothing jumps out at me but I also see we don't currently have any tests for overriding this option. I'll take a look but if you were interested in submitting a PR with a failing test that would help fast tract things :).

**Comment by iandroogmans** [comment]
Thank you for the fast reply.
I will try to set up a test case a.s.a.p.

**Comment by jtrussell** [comment]
@iandroogmans any luck reproducing this on your end? I had a chance to take quick look but the test I threw together seems to be passing:

https://github.com/iVantage/angular-ivh-treeview/commit/0531a2ee97fa64a48ee57d94b6d928de9e834226

**Comment by iandroogmans** [comment]
@jtrussell Haven't had the chance to do this. I'll add it to my agenda for this weekend.

Kind regards

**Comment by jc9412** [comment]
Hey @jtrussell, I've managed to reproduce this issue in the starter template provided. See the following link:

[http://jsbin.com/bolesaboxa/1/edit?html,js,output](link)

**Comment by jtrussell** [comment]
Feel free to re-open if this is still an issue :).
