### ISSUE TITLE
Disable collapse / expand

### ISSUE THREAD

**Issue by r4hulp** [iVantage/angular-ivh-treeview#206]
Is there any way to disable expand / collapse? we wanted to have it expanded all the time and do not want user to be able to collapse it.

**Comment by jtrussell** [comment]
There is no option to disable toggling, toggling is supported by the directive `ivh-treeview-toggle`. To "turn off" toggling you would have to use your own template and just not include that directive anywhere.

There is an option to expand everything by default use `expand-to-depth="-1"`: https://github.com/iVantage/angular-ivh-treeview#expanded-by-default.
