### ISSUE TITLE
When using the checkbox, ivh-treeview-on-item-selected has no effect

### ISSUE THREAD

**Issue by ToView** [iVantage/angular-ivh-treeview#207]
I added a callback event to ivh-treeview-on-item-selected, but did not enter the callback event when I clicked on the node.
![image](https://user-images.githubusercontent.com/23398131/30021533-4d1d776c-912d-11e7-9b60-51374499d2d9.png)

The following is my callback method:
![image](https://user-images.githubusercontent.com/23398131/30021608-8b9d59b2-912d-11e7-9dfc-7a6bcedb2ca9.png)

**Comment by jtrussell** [comment]
I think maybe you want `ivh-treeview-on-cb-change`? I don't recognize `ivh-treeview-on-item-selected`.

`https://github.com/iVantage/angular-ivh-treeview#selectdeselect-handlers`

Also, just FYI I also don't recognize `ivh-treeview-use-img-icon`.

**Comment by ToView** [comment]
Ok, thank you
