### ISSUE TITLE
 How to set the selection can only be changed by clicking on the checkbox

### ISSUE THREAD

**Issue by ToView** [iVantage/angular-ivh-treeview#208]
Is the case, I would like to click on the left side of the node checkbox to change the selection state, and do not want to click on the node when the value of the check box also changes

**Comment by jtrussell** [comment]
It sounds like you're going to  want to use the `ivhTreeviewMgr` and a node template to support changing the selection by clicking on other elements.

https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrselecttree-node-opts-isselected

Does that answer your question? If not it would be helpful to have a demo to look it.

**Comment by ToView** [comment]
Thank you. I have found a solution.

**Comment by jtrussell** [comment]
👍
