### ISSUE TITLE
On the selection status of the parent node

### ISSUE THREAD

**Issue by ToView** [iVantage/angular-ivh-treeview#211]
The parent node has a child node that is not selected, but the other child nodes are selected, and the parent node's selection state is false.Is that right?

![image](https://user-images.githubusercontent.com/23398131/31574200-2d3be780-b090-11e7-8013-8679b711cc3a.png)

**Comment by jtrussell** [comment]
Yep, that's right.

Here's the section of code that determines a parent status whenever a child changes state:

https://github.com/iVantage/angular-ivh-treeview/blob/master/src/scripts/services/ivh-treeview-mgr.js#L48-L57

A parent will be marked as selected exactly when all of its children have been marked as selected.

**Comment by ToView** [comment]
Thank you for your answer.
