### ISSUE TITLE
JSbin demos

### ISSUE THREAD

**Issue by Osophoso** [iVantage/angular-ivh-treeview#213]
I'm really very new at this so forgive my ignorance.  What is supposed to happen when I click on the demos?  Right now it takes me to JSbin (where I have an account) but there's nothing there... just the starting default jsbin template.  I can see the ivh-treeview output if I click on the "Live..." button which takes me to a page with the demo but should I not actually see the way the page was built (html, java, css, etc)?  Thanks.

**Comment by jtrussell** [comment]
Welcome to GitHub :).

You *should* see something like this:

![image](https://user-images.githubusercontent.com/732758/37096617-3114a414-21e7-11e8-9cbf-01deff1b6539.png)

With HTML, JS, and rendered output all side by side. If that's not the case then you may have found some buggy demos - I'm happy to check them out if you want to point me toward the ones causing issues. Oh - and if you don't have that **Auto-run JS** checkbox selected you will need to hit the run button before your output is rendered.

**Comment by Osophoso** [comment]
Hello.  Thanks for the welcome and the reply.   Also new to JS, Angular, ...

I basically in the HTML window there was the default template and blank everything else (Java, output, css,etc) but if I clicked on the little arrow next to the auto-run I would see the results.  In the end  I think the problem might be the security settings on my work computer (which I have no control over).  The weird thing was that it worked for some other bins, just not yours.  In the end it works on my home computer so I'll just have to manage :)

Thank you for the help!

**Comment by jtrussell** [comment]
Strange. Well, if you see more of that behavior just let me know which bins it's happening for and I'll take a look.
