### ISSUE TITLE
Get Selected Nodes Paths

### ISSUE THREAD

**Issue by tziortziskyprianou** [iVantage/angular-ivh-treeview#216]
Does the package have a function to get the selected paths from source nodes?

**Comment by jtrussell** [comment]
Nope. However if you use the included BFS service to find a node it will give you a list of parent nodes: https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewbfstree-opts-cb. I've also seen folks use the selection change callback to independently keep track of what's been selected/deselected.

We let end users change their tree structures dynamically and arbitrarily - with no restrictions on moving branches, adding nodes, etc. so keeping track of things like selected paths gets tricky.
