### ISSUE TITLE
Nothing is being selected..

### ISSUE THREAD

**Issue by spankyed** [iVantage/angular-ivh-treeview#218]
Add select functionality and some styling to the framework. Do not create a check functionality and call it selected. Nothing is being selected, its being checked. Just use the correct naming for what the feature does, ffs.

**Comment by jtrussell** [comment]
The tree nodes themselves are being marked as selected or not selected :). We're intentionally minimal in our UI but you can totally use the selected state of a node to style it as you like in your templates.
