### ISSUE TITLE
List Items from Server and apply CSS to specific parents

### ISSUE THREAD

**Issue by HelderBarreto** [iVantage/angular-ivh-treeview#221]
Hello,I am using ivh treeview on my project. I am new to angularJS, I wanted to make a treeview and I found ivh treeview. I already looked at documentation but I have some doubts. For example, on my project i have 3 roles (Admins, Managers and Employees) that are parents on treeview, and the childrens are the employees of the enterprise. I have this information on database where I am working with C# (back-end) and with angularJS on front-end. Can i list the parents and childrens from database using your ivh treeview? and how I can I  change the CSS relating to parents, I  wanted to use <b></b> only on parents. I can explain things more detailed if I am not clear

**Comment by jtrussell** [comment]
Hi @HelderBarreto, If you're using a custom template you can assign a class to nodes based on their depth in the tree. See the `depth` scope variable [here](https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#template-helper-directives). Depending on your layout, you could also accomplish the style different just with CSS. Our default layout provides supported classnames you can use. For example you could style the outermost `.ivh-treeview-node` elements differently than those within other nodes.

As far as your first question goes - you should be able to list parents and children as you described with with IVH treeview. Feel free to open a new issue if you run into specific problems.
