### ISSUE TITLE
Mark as checked

### ISSUE THREAD

**Issue by wcomnisky** [iVantage/angular-ivh-treeview#29]
Hello!

Is there a way to mark as checked some checkboxes, as in my DB?

Thanks in advance.

**Comment by jtrussell** [comment]
You can mark items as selected using the `selected` attribute (or a different one you specify with `ivhTreeviewOptionsProvider`) - I'm still putting demos together but you can take a look at [this bin](http://jsbin.com/pajeze/edit?html,output) as an example. After the initial load you can use the `ivhTreeviewMgr` to select/deselect nodes.

Does that answer your question?

**Comment by wcomnisky** [comment]
Yes! the ```selected``` attribute solved my problem. 

But I couldn't do this with ```ivhTreeviewMgr```. I don't know what I'm doing wrong, but I think it's related to getting the tree data from an AJAX (resource).

This was very helpful too:
https://github.com/iVantage/angular-ivh-treeview/blob/master/test/spec/services/ivh-treeview-mgr.js

Thanks!

**Comment by jtrussell** [comment]
Glad that helped. I'll close this for now but feel free to reopen it if you have any other questions.

You should be able to use the `ivhTreeviewMgr` to select and deselect nodes too: http://jsbin.com/mubuyihaze/1/edit.
