### ISSUE TITLE
Mark the parent as checked with a filter

### ISSUE THREAD

**Issue by wcomnisky** [iVantage/angular-ivh-treeview#30]
Hi guys!

Using this as example:
http://jsbin.com/mojub/3

If you type ```ne``` in the input filter, it will show the result list like this:
* Mustachio
  * Cane
  * Headphones

Then, if you click in the ```Mustachio``` item, all items will be checked as expected.

But if i remove the ```ne``` from the filter, you'll see that all items are checked: Mustachio, Cane, Monacle, Umbrella and Headphones.

I think the expected result is maintain just the items checked with the filter. Then, if you remove the filter, will see the items unchecked, and if you want all of them checked, you will need to click in the Mustachio again..

This is my suggestion. What do you think?
Unfortunately I don't have XP to improve this yet :disappointed:

**Comment by jtrussell** [comment]
Thanks for the suggestion, William. The checkboxes here are actually working as intended - sorry for the confusion. In other words selecting or deselecting a node should select or deselect *all* of its children regardless of whether they are visible or not.

This lets you use the filter to search for a parent in the tree and quickly select or deselect it's children.

Also, if we were to implement selection propagation as you're suggesting we'd have to constantly be updating parent node's select status as children go in and out of the view. Take your example again and check `Mustachio` but this time assume also check `Cane` and `Headphones` are also checked, it looks like this:

- [x] Mustachio
  - [x] Cane
  - [x] Headphones

No clear your filter, here's what you have:

- [x] Mustachio
  - [x] Cane
  - [ ] Monacle
  - [ ] Umbrella
  - [x] Headphones

Things get funky. Should `Mustachio` be deselected now (and indeterminate)? The user hasn't explicitly changed the selection but `Mustachio`'s children no longer all appear selected. You could make a case for only making `Mustachio` indeterminate in the first place but that would undermine our primary use case which was searching for `Mustachio` to select it.

I can see why what you're asking for would be useful but I don't see it making it into this directive, at least not as the default behavior.

Luckily, this directive is quite modular. If you need this behavior you can swap out the `ivhTreeviewCheckbox` sub-directive for one of your own design and decide what to do when a user clicks a checkbox. There was some discussion around how to do just that in [this thread](https://github.com/iVantage/angular-ivh-treeview/issues/22#issuecomment-67881988).
