### ISSUE TITLE
number of children inside the unexpanded parent node.

### ISSUE THREAD

**Issue by rasekar2000** [iVantage/angular-ivh-treeview#31]
http://wwwendt.de/tech/fancytree/demo/#sample-ext-childcounter.html
Above jQuery Tree shows the number of children inside the unexpanded parent node.
Can you please consider this as an enhancement request and please do the needful development?

Thanks and Regards,
Raj

**Comment by jtrussell** [comment]
Thanks for the feature request. At this time I don't expect we'll add what you're asking for explicitly but it's exactly the sort of thing we hope to enable by allowing you to customize node templates - [see this issue](https://github.com/iVantage/angular-ivh-treeview/issues/25). With custom templates you could very easily add an indicator for the number of children an unexpanded parent node has.
