### ISSUE TITLE
Allow multiple treeviews in a single app to be configured differently

### ISSUE THREAD

**Issue by wr0ngway** [iVantage/angular-ivh-treeview#32]
It would be nice if one had a way to configure multiple tree views differently, e.g. twistieTemplates
I'm new to angular, so this could just be ignorance on my part, but it seems like a number of items in the config are global for all tree views.

**Comment by jtrussell** [comment]
For some options (like twistie templates) there's no good way to do this at the moment. For others you can use element level attributes (like `ivh-treeview-use-checkboxes`) to customize different treeview instances.

Being able to customize all options independently seems like a reasonable feature to add though, perhaps through an `ivh-treeview-options` attribute, so I'm going to stick it on `v1.0.0` roadmap. Thanks!
