### ISSUE TITLE
Add ability to customize node display

### ISSUE THREAD

**Issue by wr0ngway** [iVantage/angular-ivh-treeview#33]
I'm trying to figure out a way to highlight a node (add a class) when the user clicks on it.  I have an onClick handler, but I only have access to the node, not to the display element, nor do I have a way to customize the template of a node.  Any suggestions on how I can do this?  If it matters, I do not need checkboxes, so have them disabled, so could use the isSelected state for marking a node as needing a highlight.

**Comment by jtrussell** [comment]
Closing this as a duplicate of #25 which, good news, is already on our short list of items for `v1.0.0`.

There's currently no supported way to accomplish what you're after (hopefully soon!) but in the near term you can work around this with a (reasonably horrible) hack by overloading the `ivh-treeview-node` directive or tapping the `ivh-treeview-node-label` class with a directive of your own making: [example](http://jsbin.com/piwegiwudu/1/edit?css,js,output).

Side note: I also added to our `v1.0.0` list to document which classes shold be expected on what elements.

**Comment by wr0ngway** [comment]
Thanks, I'll give that a shot
