### ISSUE TITLE
Filtering with object mask should consider child nodes

### ISSUE THREAD

**Issue by jtrussell** [iVantage/angular-ivh-treeview#35]
When using a pattern object as a filter expression we lose the deep searching that's built into using `filterFilter` with just a string. We should either gather the children in this case to check them as well or have visible children force their parents to also be visible.

**Comment by MattiJarvinen-BA** [comment]
:+1: damn this feature is just what I needed.

Any idea performance wise which of the implementation options would be better?

**Comment by jtrussell** [comment]
I haven't put any time into this yet to be honest. If you're interested in doing some investigation that would certainly help get this going. A PR with tests would be welcome too, just work against the v1 branch if you do get around to it :).
