### ISSUE TITLE
Filtering not working with angular version 1.3.x

### ISSUE THREAD

**Issue by nalaka526** [iVantage/angular-ivh-treeview#37]
I'm trying to use angular-ivh-treeview with angular js virsion 1.3.7. Typing into input textbox changes the nodes but is not properly filtering according to the input text.

Sample : 
http://jsbin.com/yijowifaco/2/

**Comment by jtrussell** [comment]
I believe there was a regression with filtering in angular@1.3.7 - can you upgrade to 1.3.8?

**Comment by jtrussell** [comment]
Closing this for now but feel free to reopen if upgrading angular doesn't clean up your issue.

**Comment by nalaka526** [comment]
Upgrading to  AngularJS 1.3.8 fixed the issue.
