### ISSUE TITLE
IVH treeview - Lazy loading on parent node

### ISSUE THREAD

**Issue by Saideprinz** [iVantage/angular-ivh-treeview#39]
I googled for lazy loading option on clicking of (+) sign for parent nodes. But i couldnt find any handlers for doing so on parents. Is there anyway to bind click event to (+) sign. If it is possible can you also let me know how i can get current selected node and update the JSON based on selection. 

My requirement is like user on clicking parent should load contents that will be fetched by an API call. Once its is done user might select some checkbox or all. Once all selections are done i have to send selected contents alone as JSON to save in DB. Is it possible to do, can you share some ideas. Thanks in advance.

**Comment by jtrussell** [comment]
Take a look at issue #12 for some ideas. If you're feeling ambitious you can also use [this (as yet unpublished) branch](https://github.com/iVantage/angular-ivh-treeview/tree/feat.node-templates#tree-node-templates) for setting custom node templates.

I'd suggest using the [ivhTreeviewBfs service](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewbfstree-opts-cb) if you need to track down selected nodes.
