### ISSUE TITLE
Embedded HTML in tree node

### ISSUE THREAD

**Issue by WhateverFits** [iVantage/angular-ivh-treeview#43]
I have a case where I need to have some specially formatted values place in the tree node like:

`Something <span class='blah'>special</span> goes here`

Currently it is showing the html encoded string and not the actual html elements. Is there a way to get that to work currently?

**Comment by jtrussell** [comment]
Unfortunately, there is no supported way to do this at the moment. If you're in a bind you could use the feat.node-templates branch and create a custom node template that renders the html. Options get much more hacky from there... at least for the moment.

**Comment by WhateverFits** [comment]
Thanks! That template branch looks promising. I'll check it out soon.

**Comment by WhateverFits** [comment]
Changing the template from:
`'<span class="ivh-treeview-node-label" ivh-treeview-toggle>',`
`'{{ctrl.label(node)}}',`
`'</span>'`
to:
`'<span class="ivh-treeview-node-label" ivh-treeview-toggle ng-bind-html="ctrl.label(node)">',`
`'</span>'`
accomplishes what I need to have happen.
