### ISSUE TITLE
Checking parent without automatically checking children

### ISSUE THREAD

**Issue by roryprimrose** [iVantage/angular-ivh-treeview#47]
Is there a way to configure the component so that the parent checkbox can be selected without checking all of the children?

**Comment by jtrussell** [comment]
Take a look at #22.

There have been recent developments that might help too. It may be overkill but you can create your own [custom tree node template](https://github.com/iVantage/angular-ivh-treeview#tree-node-templates) with your own checkboxes that behave as you like.
