### ISSUE TITLE
Question: Filtering and selected items ($scope instead of var)

### ISSUE THREAD

**Issue by meydey232** [iVantage/angular-ivh-treeview#50]
Hi @jtrussell 
I'm using this treeview with asp.net mvc and have a problem with displaying selected items. I had to put all items into $scope because it was only way to set them dynamically through JSON so currently I have something like this:

$scope.treeData = {};
$scope.update = function () {
        $http.post('/Home/TreeSection', data = { IdService: $scope.new.Reservation.IdServiceTest.IdService }).success(function (data) {
            $scope.treeData = data;
        });

and in my html view only: 

  data-ivh-treeview="treeData"
  data-ivh-treeview-use-checkboxes="true"
  data-ivh-treeview-filter="myQuery">

Do you have any idea how to put all selected: "true" objects into another array or how to do a copy of $scope.treeData only with selected objects dynamically?
I need this to put the selected items into database and also to display full path of selected items like: 
Mustachio/Cane/Top hat

And one more thing is filtering. It is working great but I need expanding from default 1 level into last filtered children because now I can see only the parent label and have to expand by click to the filtered value. For the better visual look i wish to have bolded result of searching ex. if I type OP would be cool if OP in Top hat would be bolded.

**Comment by jtrussell** [comment]
You can use the [`ivhTreeviewBfs` service](https://github.com/iVantage/angular-ivh-treeview#tree-traversal) to find selected items. Here's an example that grabs all the initially selected items after validating the tree: http://jsbin.com/xamifaqoyi/1/edit.

As for expanding to the nodes that are visible when there's a filter active really boils down to fully expanding the three, which you can do with the [`ivhTreeviewMgr service`](https://github.com/iVantage/angular-ivh-treeview#ivhtreeviewmgrexpandrecursivetree-node-opts-isexpanded). You can use the same service to set expansion levels as you like when the filter is removed.

For the dynamic label bolding, again there's no baked in option, but you could accomplish this fairly easily using a custom template for your nodes. I like this suggestion though, I think I'd like to add this as a custom template example so if you come up with something let me know... and I'll update this thread if I get around to it before you :smile: .

**Comment by jtrussell** [comment]
Closing this but feel free to reopen if needed!

**Comment by meydey232** [comment]
Thanks a lot. Ok so I've reached almost everything. Here's my code: http://jsbin.com/wujeqinole/1/edit

Still have two problems: 
- bolding filtered values
- expanding by clicking on plus sign (expands tree only after typing value into filter field)

Any ideas?

**Comment by jtrussell** [comment]
@meydey232 To bold filtered values you'll need to create a custom node template and essentially build your labels such that it shows the matched text in bold. If I get time I'd be willing to put something together as a custom template demo but I"m not sure I'll have a chance to get that in too soon. If you put something together though and would like feedback or to have it featured then feel free to share.

As for displaying all but the first level, you should be able give the treeview directive just the top level item's children to work with. Something like:

```
<div ivh-treeview="root.children"></div>
```

Is that what you mean?
