### ISSUE TITLE
Error: b is undefined

### ISSUE THREAD

**Issue by idlyapp** [iVantage/angular-ivh-treeview#57]
Hi, I get this error when I load my trees.

Error: b is undefined

I don't know if it's because the data for the trees isn't available directly after the page loads, they are fetched from a db and then populates the trees, any idea?

**Comment by jtrussell** [comment]
Do you have a stack trace or is that the error in its entirety?

In general there's no reason the data would need to be available when your page loads. It's tough to say where that error is coming from, it doesn't look like anything this module would generate - at least not the unminified version. Are you using minified files and if so do you get the same error using the unminified files?

**Comment by idlyapp** [comment]
with unminified I got Error: node is undefined, but I removed validate: true, and now there is no errors.
I think I didn't understand the usage of that attribute. :)

**Comment by jtrussell** [comment]
I see, I do think you will get an error if you tell the directive to validate your tree data on startup but don't actually give it any data. You can either initialize your data to an empty array or disable the validate on startup option. I'll see if we can get a better error message for this sort of thing.
