### ISSUE TITLE
click node to select it

### ISSUE THREAD

**Issue by idlyapp** [iVantage/angular-ivh-treeview#58]
My trees will always be expanded and I would like to be able to mark a node as selected by clicking it.

Is there any way to do this?

**Comment by jtrussell** [comment]
Yep. You would need to use [a custom node template](https://github.com/iVantage/angular-ivh-treeview#tree-node-templates). Just don't put the `ivh-treeview-toggle` directive on anything and use `trvw.select` to change selections if you want to keep with the same selection management strategy.
