### ISSUE TITLE
custom checkboxes

### ISSUE THREAD

**Issue by idlyapp** [iVantage/angular-ivh-treeview#59]
Hi I need some help with one thing.

I have styled some custom checkboxes, and the way I did it was to turn hide the input checkbox with display: none; and associate it with a label. this seemed like the way most did it.

The problem I have now is that I can't add ng-change to a label, to be able to toggle the checkboxes like it's done in the regular template, it's working with ng-click="trvw.select(node, isSelected)" to select a node but not to deselect.

Any suggestion?

**Comment by jtrussell** [comment]
Would you mind using the jsbin template in the readme to create an example of what you're trying?

**Comment by idlyapp** [comment]
I guess I didn't do it in the best way, since I didn't know how to add a label to only the input tag using custom templates I added it directly to the treeview.js

So I don't know if it's to time consuming for you to show how you would go about to add customized checkboxes instead of the defaults?

Here is a small sample of what I mean.

   ` template: [
      '<input type="checkbox" class="styled"',
        'ng-model="isSelected"',
        'ng-change="trvw.select(node, isSelected)" />',
        '<label class="checkbox" ng-model="isSelected" ng-click="trvw.select(node, isSelected)" > </label>'
    ]`

and the css

`input[type=checkbox] {
 display:none;  
}
input[type=checkbox] + label{
    background: url("../img/unchecked.svg") no-repeat;
    height: 10px;
    width: 10px;
    display:table-cell;
    padding: 0 0 0 0px;
    cursor: pointer;
}
input[type=checkbox]:checked + label{
background: url("../img/checked.svg") no-repeat;
height: 10px;
width: 10px;
display:table-cell;
padding: 0 0 0 0px;
cursor: pointer;
}`

The checkboxes get the design I want but I'm not able to use ng-change on it as the default checkbox does because in my case I'm hiding the default checkbox and style the label as a checkbox instead.

And with ng-click I'm just able to select checkboxes not deselect..

It's also very possible my approach was completely wrong here! :)

**Comment by jtrussell** [comment]
Closing this but one of the custom template demos swaps our the usual checkboxes for ascii art ones, might be of interest: http://jsbin.com/fokunu/edit?html,js,output
