### ISSUE TITLE
Backwards compatibility with 1.1.5 - Strange issue

### ISSUE THREAD

**Issue by milesburton** [iVantage/angular-ivh-treeview#63]
Hey all,

I'm unfortunate enough to have to back port the tree view component to Angular 1.1.5.

Everything seems to be fine for the most but except the expand/contract functions of each node

http://jsbin.com/vebuwizale/edit?html,css,js,output

It appears as if $scope.apply loses the "node" context.

Obviously it's best to focus on A1.4+ but if anyone has any quick thoughts why this could be broken I'd appreciate it.

Cheers

**Comment by jtrussell** [comment]
Did angular at 1.1.5 support `controllerAs` in directives? It looks like the docs stop at 1.1.4 so I'm not totally sure. In any event it seems as though in the demo above `scope.trvw` is undefined which ought to be coming in via the [controllerAs: 'trvw'](https://github.com/iVantage/angular-ivh-treeview/blob/master/src/scripts/directives/ivh-treeview.js#L54) declaration.

You could try refactoring to not use `controllerAs` or maybe just tacking a `trvw` property onto `$scope`?... not sure.

I don't think we'll be making changes on that scale to support 1.1.x but if you turn up anything small we can do to help give a shout!

**Comment by milesburton** [comment]
Thanks, I'll take a look through and see if that'll work and let you know. Wouldn't in a million years ask you to make changes to the core library for support an ancient version :)

**Comment by jtrussell** [comment]
Closing this but feel free to add comments if we can be of any help.
