### ISSUE TITLE
How to highlight the current label?

### ISSUE THREAD

**Issue by cdanyl** [iVantage/angular-ivh-treeview#64]
Is there a way to highlight the current node.label?!

PS: My tree don't use checkbox fonctionnality.

**Comment by jtrussell** [comment]
What do you mean by current?

**Comment by cdanyl** [comment]
For example, add a css class to the current clicked element in the tree!

**Comment by jtrussell** [comment]
Would you mind creating a jsbin of what you're attempting using the template in the readme? It'll be easier to work through if we have running code.

**Comment by jtrussell** [comment]
Closing but feel free to reopen with a bin/plunk/etc.

**Comment by Thirumalaimurugan** [comment]
How to highlight Most recently expanded
