### ISSUE TITLE
Indeterminate checkbox click do not work in IE/Edge

### ISSUE THREAD

**Issue by BDomzalski** [iVantage/angular-ivh-treeview#72]
When you click a node checkbox which is in indeterminate state subtree selection state doesn't change accordingly.
Observed in IE11 and Microsoft Edge at Windows10.

**Comment by jtrussell** [comment]
Confirmed - seems to IE specific.

**Comment by jtrussell** [comment]
Some browsers (IE, ...?) don't fire change events when a checkbox loses it's indeterminate state. This means `ng-change` expressions aren't run :(.

**Comment by jtrussell** [comment]
Interesting approach to dealing with this issue: http://stackoverflow.com/a/19447939

**Comment by jtrussell** [comment]
Published under the `v1.0.0-rc.3` tag - thanks, @evsheffield!
