### ISSUE TITLE
Not (yet) existing property set as ivh-treeview throws exception

### ISSUE THREAD

**Issue by BDomzalski** [iVantage/angular-ivh-treeview#73]
When a property pointed by ivh-treeview in a template is not present the tree throws exception. The same way it behaves when mentioned value is null.
As binding for ivh-treeview property is defined in a html/template this seems to be common use case when data are retrieved in an async operation.

**Comment by jtrussell** [comment]
Sorry, I'm not entirely sure what you mean. Would you mind providing a demo?

**Comment by BDomzalski** [comment]
Created a jsbin https://jsbin.com/jayuci/7/edit?js,console

Generally what I mean is that control should handle without exceptions situation when in html you define ivh-treeview="noYetPresentScopeProperty" and validate=true (as it turns out when I was preparing example).
Rest of my comment was to show that such use case is correct and common - mentioned property is created and populated with some async code (like when ajax response received; in the example I used $timeout to simulate).

Hope now I make it clear.

**Comment by jtrussell** [comment]
I see, thanks. You should be able to use the **v1.0.0-rc.2** tag to no longer have validate throw when you give it a non-tree.

In general though the `validate` just affects how we handle data present at the time the tree is initialized. Right now we make no attempt to validate data added to the tree later, it would be on the user to validate anything added to your tree store after the fact - at least for the moment.

**Comment by jtrussell** [comment]
Let me know if that new tag doesn't clear things up for you.

We'll have to revisit validating nodes added on the fly as a possible future enhancement.

**Comment by BDomzalski** [comment]
Looks like the case is now handled fine. Shame I won't need that anymore - moved away from validate=true in favor to ensure in at my code.

By the way - in ivh-treeview.js you have newline characters in mixed formats (mostly LF but some CR LF).

**Comment by jtrussell** [comment]
Ah, it's possible. I do some of my development in windows. I've got git set to check in with unix style line endings but I suppose some things slipped through the cracks.
