### ISSUE TITLE
how to reload the tree when the data is changed ?

### ISSUE THREAD

**Issue by Kuroky360** [iVantage/angular-ivh-treeview#75]
for exp: the data is empty at the first,then the data is filled; how to refresh the tree

**Comment by jtrussell** [comment]
You shouldn't have to do anything special to add data to your tree - that is to say the new nodes should show up in the tree as you would expect. You may need a `$scope.$apply()` if the data is added outside the scope of angular.

However, IVH Treeview won't attempt to do any selection validation when you add or remove nodes on the fly. So just keep in mind that when you add or remove nodes you'll need to either set their selected status yourself or use `ivhTreeviewSelectionMgr.validate` to validate the tree or individual branches.

Does that answer your question?

**Comment by Kuroky360** [comment]
OK, thanks! 
got it!
it's my mistake!

**Comment by jtrussell** [comment]
:+1: Sorry for the confusion!
