### ISSUE TITLE
Review: gh-pages

### ISSUE THREAD

**Issue by jtrussell** [iVantage/angular-ivh-treeview#76]
Any takers @evsheffield or @lily-pytel?

Pages to review: http://ivantage.github.io/angular-ivh-treeview/

Maybe we should link to jsbin demos for the examples?

**Comment by jtrussell** [comment]
Tagging #27

**Comment by evsheffield** [comment]
I'm happy to take a look! Anything in particular you're looking for in review? Example variety, correctness, typos, etc.?

**Comment by jtrussell** [comment]
Yep - and generally whether anything feels missing or unnecessary.

**Comment by lily-pytel** [comment]
Will take a look as well!

**Comment by evsheffield** [comment]
Fixed a couple of small mistakes:
- https://github.com/iVantage/angular-ivh-treeview/commit/a8e9003f150d69d42f2139350ebd761346cafa18
- https://github.com/iVantage/angular-ivh-treeview/commit/f3e2cc86f0a19f648f730403b6e964ff74a97828

**Comment by evsheffield** [comment]
I thought it might be useful to include a demo for `ivhTreeviewBfs` so I whipped one up:
https://github.com/iVantage/angular-ivh-treeview/pull/80
