### ISSUE TITLE
Cursor style should not be "pointer" for leaf nodes

### ISSUE THREAD

**Issue by evsheffield** [iVantage/angular-ivh-treeview#77]
Leaf nodes (both the twist-tie and actual text) show a pointer when hovering over them which implies clicking them would do something, but it currently does not. If there were a click action for leaf nodes, it might be to toggle the checkbox, but that could be confusing given that the click behavior for all non-leaf nodes is to expand/collapse the branch. It may be best to simply not show the cursor as a pointer for leaves.

**Comment by jtrussell** [comment]
Agreed - that's set by the basic theme: https://github.com/iVantage/angular-ivh-treeview/blob/master/src/styles/ivh-treeview-theme-basic.less#L9-L11
