### ISSUE TITLE
Review: README

### ISSUE THREAD

**Issue by jtrussell** [iVantage/angular-ivh-treeview#78]
Hey @alexmiddeleer mind taking a look see at some point? Anything unclear or could use more fleshing out?

https://github.com/iVantage/angular-ivh-treeview/tree/v1

**Comment by alexmiddeleer** [comment]
`This is only relevant if you validate your tree data using ivhTreeviewMgr.validate which will assume this state by default`. I thought this sentence was slightly confusing--the this is only relevant if part is a little vague. It's pretty easy to figure out though if you play with the demo, so don't lose any sleep over it.

**Comment by alexmiddeleer** [comment]
`You may also supply a toggle hanlder` sp

**Comment by alexmiddeleer** [comment]
`ivhNode, the node that was toggled; and ivhTree, the tree it belongs to; ivhIsExpanded, whether or not the node is now expanded.` Remove or shift over the `and`.

**Comment by alexmiddeleer** [comment]
another `hanlder` spotting

**Comment by jtrussell** [comment]
How embarrassing, I think this calls for: `:iab hanlder handler`

**Comment by jtrussell** [comment]
@alexmiddeleer That new default selected state any more clear?

**Comment by lily-pytel** [comment]
This is easily confirmed in the demo but maybe a note [here](https://github.com/iVantage/angular-ivh-treeview/blob/master/README.md#expanded-by-default) about how if you try to expand to a depth deeper than the tree has, it just looks fully expanded.

**Comment by jtrussell** [comment]
Fair enough. Any on thoughts on that defaulted selected state @lily-pytel?

Mind taking a look at some point too @kevingrammer?
