### ISSUE TITLE
can I achieve a tree table page as below by the ivh?

### ISSUE THREAD

**Issue by Kuroky360** [iVantage/angular-ivh-treeview#79]
the page like this:
![image](https://cloud.githubusercontent.com/assets/10414243/9953056/c2132c2c-5e0f-11e5-96b5-c4a6857c4f79.png)

may use the template I think

**Comment by jtrussell** [comment]
Sure. At least I can't think of a particular reason why not. And yes, you would need a custom template. Shoot me an email if you run into issues.
