### ISSUE TITLE
Allow leaf nodes to have no check boxes [Enhancement Request]

### ISSUE THREAD

**Issue by vediga** [iVantage/angular-ivh-treeview#82]
My use case will need the leaf nodes in the tree to have no checkboxes. Is it possible to add this enhancement/customization where I can specify 'hideLeafNodeCheckbox' in the config or something more generic which lets us hide the checkboxes at any level. Thanks !!

**Comment by jtrussell** [comment]
I'm not sure we'd add an explicit config option for this but you can do it already with a bit of CSS and or your own node templates if you really need fine control.

Using the default template you have access to a number of supported classnames that can help you out: https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#tree-layout. So augmenting the basic skin provided with something like this should serve to hide checkboxes for leaf nodes :

```css
.ivh-treeview-leaf .ivh-treeview-checkbox-wrapper {
  display: none;
}
```

If you need checkboxes removed entirely from the DOM the treeview controller has an `isLeaf` method which is available to node templates (`trvw.isLeaf(node)`) you can use in conjunction with `ng-if` to completely remove a node from the DOM.

You also have access to a `depth` variable within your node template which I see now isn't documented but should be (I'll add it shortly).

Does that help?

**Comment by vediga** [comment]
Thanks a lot Justin. That really helps.

On Thu, Oct 1, 2015 at 5:57 PM, Justin Russell <notifications@github.com>
wrote:

> I'm not sure we'd add an explicit config option for this but you can do it
> already with a bit of CSS and or your own node templates if you really need
> fine control.
>
> Using the default template you have access to a number of supported
> classnames that can help you out:
> https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md#tree-layout.
> So augmenting the basic skin provided with something like this should serve
> to hide checkboxes for leaf nodes :
>
> .ivh-treeview-leaf .ivh-treeview-checkbox-wrapper {
>   display: none;
> }
>
> If you need checkboxes removed entirely from the DOM the treeview
> controller has an isLeaf method which is available to node templates (
> trvw.isLeaf(node)) you can use in conjunction with ng-if to completely
> remove a node from the DOM.
>
> You also have access to a depth variable within your node template which
> I see now isn't documented but should be (I'll add it shortly).
>
> Does that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iVantage/angular-ivh-treeview/issues/82#issuecomment-144890585>
> .
>



-- 
Thanks & Regards,
Vikas Ediga.

**Comment by jtrussell** [comment]
Just a minor edit - it's correct in the docs but I made a typo in the css rule above, it should be correct now.

Feel free to reopen this if needed.
