### ISSUE TITLE
Can not arrived to awesomeCallback and otherAwesomeCallback at tree view click

### ISSUE THREAD

**Issue by syaung** [iVantage/angular-ivh-treeview#85]
Old treeview version is slow to load over 5000 items. So I changed with latest version.
It can load more faster than old version.
But latest version, It can not arrived to awesomeCallback and otherAwesomeCallback.
ivh-treeview-click-handler="awesomeCallback
ivh-treeview-change-handler="otherAwesomeCallback"

**Comment by jtrussell** [comment]
In case anyone else arrives here with the same question, the click and change callbacks are handled different in v1.x. You can see the [migration](https://github.com/iVantage/angular-ivh-treeview/blob/master/MIGRATING.md) doc for a full list of breaking changes (not many more).

@syaung  As for performance on large trees, you will likely see a significant performance boost by using a custom templates which adds an `ng-if` to the treeview children directive. See [this comment](https://github.com/iVantage/angular-ivh-treeview/issues/62#issuecomment-123205552).
