### ISSUE TITLE
name Attribute

### ISSUE THREAD

**Issue by fanpes** [iVantage/angular-ivh-treeview#90]
Actually this treeview dont have a way to set the name attribute to each checkbox

**Comment by jtrussell** [comment]
No, there is not a direct way to set the name attribute of a checkbox. Might I ask what your use case is?

**Comment by fanpes** [comment]
well in this moment my solution was edit  your script to set a param "name" to set it  in the model so because i have to send the info of the checkboxes tree generated in a form data.
