### ISSUE TITLE
Is there any way to increase performance?

### ISSUE THREAD

**Issue by nikita-yaroshevich** [iVantage/angular-ivh-treeview#92]
Please would you be so kind to suggest any good way to increase performance of this widget?
I noticed that it creates a new scope for every item and every leaf. It cause a performance penalty when I try to load about 300 elements. My form stuck while tree data loading. And time to time when I try to manipulate it (scopes updates).
I will be very appreciated for any your suggestion. 

Thanks in advance

**Comment by jtrussell** [comment]
Have you tried implementing any of [these suggestions](https://github.com/iVantage/angular-ivh-treeview#optimizations-and-known-limitations)?

**Comment by nikita-yaroshevich** [comment]
Yep, sorry( I missed that point. 
My bad.

Thanks for fast response)

**Comment by jtrussell** [comment]
Cool - let us know how that works for you!

**Comment by vivek380** [comment]
Hi russell, in our case we have to show all the nodes as expanded only do the ng-if option for children don't matter. We have around 4k records coming that we need to bind it to the tree and it really takes a lot of time to show Popup. We already have data available to bind but binding itself is taking too much time.

Also the second option mentioned to use bind once of angular is of no used for us as we are using one tree for many popups i.e bind data keeps changing. For some we have less data like few hundred but in one perticular case we have around 4k data coming which takes lot of time to bind and display popup.

Can you suggest any other way to improve performance ?

**Comment by jtrussell** [comment]
Hi @vivek380 to be honest I think you're going to have a very tough time representing four thousand dynamically bound elements with this directive - or with Angular in general. Even with just a single watcher per node your app is going to feel pretty sluggish for many users.

At one point the Angular team suggested that folks try to keep their total watcher count under 2k for best performance. You're already talking about ten times that number without any dynamic binding - fully stripped down this directive uses about 5 watchers per visible node IIRC.

The strategy for optimizing here is really the same as any other performance degradation scenario in Angular driven by high watcher counts: eliminate watchers. The default template is pretty greedy in terms of watchers created but if you know which template components must be dynamic you can bind-once everything else and save yourself a huge number of total watchers.

I wish I had better suggestions for you but I guess I would first ask if you do absolutely need to show the entire tree expanded at once? It seems unlikely that a user will be able to meaningfully interact with 4k nodes. Can you perhaps just fully expand a single root branch at a time (etc.)? Failing that you can get creative with a custom template - e.g. update nodes when an event is broadcast, etc. If all else fails you might want to consider simply stepping outside Angular for your treeview, e.g. hand off the data to some jQuery plugin that does trees if that makes more sense with how you want to interact with the data.

**Comment by vivek380** [comment]
Hi @jtrussell, on the requirement side we have agree to show only the selected nodes as expanded  and rest all as collapsed. So now we were trying the solution with custom template as suggested in the performance link, however the proposed solution works fine with on line available ivh-treeview.js library but with the licensed version proposed solution doesn't seems to work.

Sample available at " http://jsbin.com/momuro/2/edit?html,js,output " works fine but does not work with licensed library. 
<script type="text/ng-template"> does not seems to work in our case. and it always load data with default template.

Can you suggest any way by which we can use this suggested code in our application where we are using licensed library ?

We need to use this solution on priority. Thanks in advance.

**Comment by jtrussell** [comment]
I'm sorry - are you using npm to install angular-ivh-treeview? It looks like the most recenter version did not get published to npm - so I just did. You should be able to get v1.0.2 (the latest version) with npm, bower, etc. now. Does that clear things up for you?

**Comment by vivek380** [comment]
Thanks @jtrussell  this seems to working with latest library. 

Also i have noticed one thing that expandTo and expandRecurrsive does not seems working properly with custom templates.

Do you have any working example for expandTo and expandRecurrsive with Custom template ?

**Comment by jtrussell** [comment]
Hmm - are you using the provided `ivh-treeview-children` directive in your custom template and do you have the main css file included on the page? The children directive should be adding the appropriate classes to hide/show nodes.

I don't have an example handy but I can put something together - do you happen to have an example of it not working?

**Comment by vivek380** [comment]
Hi , here is the link : http://jsbin.com/payudu/edit?html,js,output

I basically updated the already available example for expandTo with custom template in HTML. So if you check without custom template in html expandTo works fine however if we include custom template code if you click on expand button it expands one level down and then if you will click again it will expand to the second level. 

It does not expand to the desired second level by just one click.

**Comment by vivek380** [comment]
Hi @jtrussell , were you able to validate. I needed to use expandTo with custom template on priority.

Thanks a lot for your support !!!

**Comment by jtrussell** [comment]
Yes still doing some investigation but I believe it is a bug - I created a new issue for it here #104.

**Comment by jtrussell** [comment]
@vivek380 should be good in version 1.0.3!

**Comment by vivek380** [comment]
@jtrussell , Thanks this is working g8 !!

**Comment by vivek380** [comment]
Hi @jtrussell , do you have any suggestion to show nodes expanded as we do search with filter if all the nodes are already collapsed.

I tried looking into earlier posted issues on the forums but could not get any thing concrete.

Will be good if you have any working example for the same :)

**Comment by jtrussell** [comment]
@vivek380 The tools are available but there's no built in way to do it, I've never personally implemented this though (anybody?). In theory you just have to fully expand the tree when there's an active filter: `ivhTreeviewMgr.expandRecursive(tree)`. Then return the tree to it's previously expanded state when there's no longer a filter... or whatever you decide is appropriate (e.g. what happens to nodes that are expanded/collapsed by the user while filtering?). This probably means taking a snapshot of each node's toggled state, I'd likely cheat and traverse the tree and collecting `node[ivhTreeviewOptions().expandedAttribute]` along the way. If that feels weird you could go over the top and make a deep copy of the tree pre-filter then swap the copy in after filtering is done. Pretty wasteful but it would work. Hope that helps!
