### ISSUE TITLE
Customize nodes/labels

### ISSUE THREAD

**Issue by theBojke** [iVantage/angular-ivh-treeview#93]
I'm trying to customize my nodes by some internal condition i.e. to highlight specific leafs or nodes that meets some condition inside my app (Let's say I want to highlight only leafs with label length longer that 5 letters). Something simmilar to issue #33 but not on the selecting event. Is there a way to do this in new release?

**Comment by jtrussell** [comment]
Absolutely, check out the docs for skinning/custom templates: https://github.com/iVantage/angular-ivh-treeview/blob/master/docs/templates-and-skins.md.

That what you were looking for?

**Comment by theBojke** [comment]
Probably, but I'm not sure is it possible to use trvw.label(node) conditionaly. I need lables higlighted when tree is rendered.

**Comment by jtrussell** [comment]
If you need something really custom you'll be best served by creating your own template with your own label rendering logic baked in.

`app.directive('myLabel', function() { /* highlight short labels */ })`

Just use that guy in your template :).

**Comment by jtrussell** [comment]
Feel free to reopen if more info is needed :smile:.
