### ISSUE TITLE
Option to turn of Indeterminate state

### ISSUE THREAD

**Issue by martitv** [iVantage/angular-ivh-treeview#94]
Hi, trying to make a selection tree where you are able to select parent-nodes as well as a selection(not necessarily all) of its children-nodes.

At the moment, this seems like it is not possible as the parent-node becomes indeterminate(false) when a child-node is deselected.
This means that using the bfs function to look for nodes that are selected, doesn't work.
Can't really check for the __indeterminate value either as there is no way to know if it was selected or not before it became indeterminate.

Or is there a way that i haven't thought of yet?

Also, there should be a way to turn off the auto-selection/deselection of all children-nodes when selecting/deselecting parent-node. Very annoying feature sometimes.

Heres a plunker of the problem:
http://plnkr.co/edit/2ioHZvhiAeW4O8urIjDE?p=preview

Try to deselect "Fountain" and click "get selected"-button. You will see that "Pens" is not there.

**Comment by jtrussell** [comment]
I don't see the built in selection management changing any time soon. That being said, all of the selection logic is routed through the template checkboxes, if you're using your own template you can provide your own checkboxes that do whatever you like when they're clicked.

In a similar vein, with our own applications we have a notion of "excluding" child nodes of a selected parent. Here's a rough sketch of what that might look like just as food for thought:

http://jsbin.com/gewuca/edit?html,output

We end up considering top most selected nodes as "selected" then search for "excluded" nodes among their children. Again, I'm not saying that will work for you exactly but there's lots of flexibility in being able to use your own templates.

**Comment by jtrussell** [comment]
Feel free to reopen if needed :).

**Comment by martitv** [comment]
Hi, trying to create a directive that lets me select nodes by clicking the label.
Currently it is not working so well due to the scope i get in the directive is not the scope i want.

This is my directive(tried to follow your example):
```javascript
.directive('labelSelect', ['ivhTreeviewMgr', function(ivhTreeviewMgr){
        return {
            restrict: 'A',
            template: '',
            link: function($scope, $elm, $attrs){
                console.log($ctrl);
                $elm.on('click', function(){
                    ivhTreeviewMgr.select($scope.tree_content, $scope.node, !$scope.node.selected);
                    $elm.toggleClass('node-selected', !$scope.node.selected);
                    $scope.$apply();
                })
            }
        }
    }]);
```

Controller:
```javascript
angular.module('myApp.thing', [])
.controller('ctrl', function(){
$scope.tree_content = [
            {
            label: 'Hats',
            children: [
                {label: 'Flat cap'},
                {label: 'Fedora'},
                {label: 'Baseball', selected: true},
                {label: 'Top hat'},
                {label: 'Gatsby'}
            ]
        },{
            label: 'Pens',
            selected: true,
            children: [
                {label: 'Fountain'},
                {label: 'Gel ink'},
                {label: 'Roller ball'},
                {label: 'Fiber tip'},
                {label: 'Ballpoint'}
            ]
        },{
            label: 'Whiskey',
            children: [
                {label: 'Irish'},
                {label: 'Scotch'},
                {label: 'Rye'},
                {label: 'Tennessee'},
                {label: 'Bourbon'}
            ]
        }];

        $scope.tree_options = {
            twistieCollapsedTpl: '<span class="glyphicon glyphicon-chevron-right"></span>',
            twistieExpandedTpl: '<span class="glyphicon glyphicon-chevron-down"></span>',
            twistieLeafTpl: '&#9679;',
            nodeTpl: [
                '<div>',
                '<span ivh-treeview-toggle>',
                '<span ivh-treeview-twistie></span>',
                '</span>',
                '<span class="ivh-treeview-node-label" label-select ivh-treeview-toggle>',
                '{{trvw.label(node)}}',
                '</span>',
                '<div ivh-treeview-children></div>',
                '</div>'
            ].join('\n')
        }
});
```
HTML:
```html
<div ivh-treeview="tree_content"
                ivh-treeview-options="tree_options"
                ivh-treeview-use-checkbox="false"></div>
```

When i try to click the labels i get node.children is undefined from the bfs function. Probably because $scope.tree_content is undefine.

How can i get my controllers scope into the directive? or how can i let the directive see the tree_content?

Thanks.
