### ISSUE TITLE
Is there a way to select only nodes, that are not filtered

### ISSUE THREAD

**Issue by FSou1** [iVantage/angular-ivh-treeview#96]
When i filtered any of tree nodes with `ivh-treeview-filter="actions.filter"` function and tried to use `ivhTreeviewMgr$.selectAll(tree, {}, true)` function,- filtered child nodes were selected too.

Is there a way to select only not filtered nodes (or check/iterate over each of nodes in a tree with filter function before select it).

**Comment by FSou1** [comment]
`ivhTreeviewBfs$` helped me with iterating over tree and selecting filtered (with my custom function) nodes:

`
                                ivhTreeviewBfs$(tree, {}, function(node) {
                                    if(this.filter(node)) {
                                        ivhTreeviewMgr$.select(tree, node, {}, selected);
                                    }
                                }.bind(this));
`

**Comment by FSou1** [comment]
Unfortunately, `ivhTreeviewMgr$.select` mark selected childs & parents, so the easiest way to select only single node is:
```javascript
ivhTreeviewBfs$(tree, {}, function(node) {
    node.selected = myFilter(node);
}.bind(this));
```
Looks not good =\

**Comment by jtrussell** [comment]
`ivhTreeviewMgr.select` & co. aims to always leave your tree in a consistent selected state: all of a selected node's children are selected, parent's are updated when children change selected status, etc. There's no way to guarentee this behavior if we ignore nodes that are filtered out - suppose the filter changes yet again (or is removed completely) everything would be out of whack.

There's nothing wrong with what you're trying to do, it's just not consistent with the selection management built into IVH Treeview, you'd have to implement your own selection management.

**Comment by FSou1** [comment]
Ok, is there a way i could control select/deselect of children nodes? If i have my custom filter function and i clicked select to a node, that has childrens- i'd like to have a possible to control of selecting (or prevent selecting if it's filtered) child nodes.

**Comment by jtrussell** [comment]
You can use your own checkbox in your template instead of the one that comes with the default template and handle clicks there.

**Comment by jtrussell** [comment]
Feel free update this  thread with additional question but I'm going to close the issue for now.
