### ISSUE TITLE
Prevent hiding filtered nodes in tree

### ISSUE THREAD

**Issue by FSou1** [iVantage/angular-ivh-treeview#98]
Dear developers, i have a task to mark filtered nodes of tree with custom css class and do not hide them. As you can see, marked orange with text-decoration: line-throught nodes was filtered, but i still need to display it:

![image](https://cloud.githubusercontent.com/assets/1132431/11361590/8dfcede6-929f-11e5-8805-4891ad725d36.png)

For now, i could do this only comment next lines in sources:
```javascript
    template: [
      '<ul class="ivh-treeview">',
        '<li ng-repeat="child in root | ivhTreeviewAsArray"',
            //'ng-hide="trvw.hasFilter() && !trvw.isVisible(child)"', <-- this
            'ng-class="{\'ivh-treeview-node-collapsed\': !trvw.isExpanded(child) && !trvw.isLeaf(child)}"',
            'ivh-treeview-node="child"',
            'ivh-treeview-depth="0">',
        '</li>',
      '</ul>'
    ].join('\n')
```
and this:
```javascript
    template: [
      '<ul ng-if="getChildren().length" class="ivh-treeview">',
        '<li ng-repeat="child in getChildren()"',
            //'ng-hide="trvw.hasFilter() && !trvw.isVisible(child)"', <-- this
            'ng-class="{\'ivh-treeview-node-collapsed\': !trvw.isExpanded(child) && !trvw.isLeaf(child)}"',
            'ivh-treeview-node="child"',
            'ivh-treeview-depth="childDepth">',
        '</li>',
      '</ul>'
    ].join('\n')
```

**Comment by jtrussell** [comment]
Something like this?

http://jsbin.com/kuwoyam/1/edit?html,css,output

That's just a hack (we only use ng-hide for filtering) but I could get behind adding a custom class for filtered out nodes rather than just using ng-hide if that's what you're looking for.

**Comment by jtrussell** [comment]
Actually - on second though it might be better for us to stick with ng-hide so folks can take advantage of ngAnimate... I'm open to suggestions :).

**Comment by FSou1** [comment]
Yeap, hack with css `li.ivh-treeview-node.ng-hide` looks not so bad. Right now i'm looking for a way of prevent hiding and possible to apply styles for filtered nodes, so i'm ready for all kinds of you implementation desicion :) Sry for my bad english

**Comment by jtrussell** [comment]
Cool - I'm thinking we'll just end up supporting `.ivh-treeview-node.ng-hide` so we can stand on the back of ngAnimate for filtering. I'd say you should feel free to override that class now your purposes here as in the demo above. I'll update the docs to include it.
