### ISSUE TITLE
selectEach methond can only use string Ids

### ISSUE THREAD

**Issue by furoTmark** [iVantage/angular-ivh-treeview#99]
For a tree that has numeric IDs, the ivh-treeview does not select anything.
Example: http://jsbin.com/daduhekeqo/edit?html,js,output

And on line 948 I found:
     
    var useId = ng.isString(node);

This should be checked
I think it should be 

    var useId = !ng.isObject(node);

**Comment by jtrussell** [comment]
Thanks for pointing this out, we should be able to get a fix in shortly.
